name: "Publication suggestion"
description: "Suggest an AI quickstart for publication on redhat(dot)com"
title: "[pub suggestion]: <insert descriptive title here>"
labels: 
  - publication_suggestion
body:
  - type: markdown
    id: summary
    attributes:
      value: |
        ## Publication suggestion

        Thank you for suggesting a quickstart for publication on redhat(dot)com!

        Please complete the fields below and leave checkboxes unchecked.
  - type: input
    id: repo_link
    attributes:
      label: Quickstart repository link
      description: Paste a link to the quickstart repository you recommend to publish
      placeholder: "https://github.com/rh-ai-quickstart/best-quickstart-ever"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: (Optional) Briefly describe why this quickstart should be prioritized for publication
      placeholder: "Explain the quickstart's purpose, target audience, impact and why it's needed."
  - type: checkboxes
    id: readiness
    attributes:
      label: Publication readiness checklist
      options:
        - label: README is clear, concise, and free of typos
        - label: README is accurate and includes vertical use case
        - label: README is complete and follows template structure
        - label: Quickstart runs end-to-end without errors and is reproducible
        - label: Titles, descriptions, and tags adhere to MIST guidelines
        - label: Insert redhat(dot)com requirements here
        - label: Technical review complete
        - label: Peer review complete
        - label: Known issues and requests are documented (or resolved)
